### ISSUE TITLE
Handshakejs needs a Logo

### ISSUE THREAD

**Issue by motdotla** [handshakejs/handshakejs-script#7]
A good logo will help legitimize Handshakejs in the minds of others.

It's also the first step toward a mini-site for the project - which will further help spread the adoption of it. Further adoption will help spur more development.

Given that logic, I decided to have a logo designed on 99designs (I've had good luck w/ 99designs in the past).

Here's the link to the project: http://99designs.com/logo-design/contests/help-make-handshake-js-well-known-open-source-378728/entries

Share your thoughts on the logos. Write your thoughts here.

**Comment by motdotla** [comment]
The contest is just getting started, but there are already some good ones. I think these are pretty cool so far:

![screen shot 2014-05-07 at 5 52 22 pm](https://cloud.githubusercontent.com/assets/3848/2910753/25780cae-d64b-11e3-9ad2-e20438d074f1.png)

![screen shot 2014-05-07 at 5 52 26 pm](https://cloud.githubusercontent.com/assets/3848/2910754/296fe944-d64b-11e3-8803-7e26969937a5.png)

**Comment by arthurnn** [comment]
48 , and 32 are pretty good too IMO

**Comment by davidguttman** [comment]
This one reminds me of something... butt can't think of what...

![](http://d8u1nmttd4enu.cloudfront.net/designs/35562608~d01d950b2b94f86698a330e5e7fc58eb10fc891e-original)

**Comment by davidguttman** [comment]
And more seriously, I like the ones with the lock theme better, makes it clear that this is an auth product. I like the one you have above, this one is pretty good too (although it reminds me of the BofA logo).

![](http://d8u1nmttd4enu.cloudfront.net/designs/35615601~194db56ae986fcc58664a4799dadb60870bb3c7c-original)

**Comment by motdotla** [comment]
haha, what could that be... :)

good feedback. thanks.
